FROM node:13-alpine
EXPOSE 3000

RUN npm install -g typescript
RUN npm install -g ts-node
RUN npm install -g ts-node-dev

# nest
RUN npm install -g @nestjs/cli

# ncu -u
RUN npm install -g npm-check-updates

RUN npm install -g npm